name: Prisma Cloud Compute Image Scan

on: [push, pull_request]

jobs:
  build-and-scan:
    name: Build and Scan Image
    runs-on: ubuntu-latest

    permissions:
      contents: read # 🔥 Explicitly set permissions to avoid 'write-all'

    env:
      PRISMA_CLOUD_URL: "https://api3.prismacloud.io"
      DOCKER_IMAGE: "ghcr.io/${{ github.repository }}/apache-app:latest"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set Up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .
          docker tag ${{ env.DOCKER_IMAGE }} ghcr.io/${{ github.repository }}/apache-app:latest

      - name: Download TwistCLI from Prisma Cloud Compute Console
        run: |
          curl --insecure --user ${{ secrets.TL_USER }}:${{ secrets.TL_PASS }} \
               --output ./twistcli \
               ${{ secrets.PATH_TO_CONSOLE }}/api/v1/util/twistcli
          chmod a+x ./twistcli

      - name: Scan the Image
        run: |
          ./twistcli images scan --address ${{ secrets.PATH_TO_CONSOLE }} \
                                 --user ${{ secrets.TL_USER }} \
                                 --password ${{ secrets.TL_PASS }} \
                                 --details \
                                 ${{ env.DOCKER_IMAGE }}
