name: Prisma Cloud Compute Image Scan

on: [push, pull_request]

permissions:
  contents: read

env:
  PRISMA_CLOUD_URL: "https://api3.prismacloud.io"
  DOCKER_IMAGE: "ghcr.io/${{ github.repository }}/apache-app:latest"

jobs:
  build-and-scan:
    name: Build and scan image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set Up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .
          docker tag ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_IMAGE }}

      - name: Download twistcli from the Prisma Cloud Compute Console
        run: |
          curl --insecure --user ${{ secrets.TL_USER }}:${{ secrets.TL_PASS }} --output ./twistcli https://${{ secrets.PATH_TO_CONSOLE }}/api/v1/util/twistcli
          chmod a+x ./twistcli

      - name: Scan the image
        run: |
          ./twistcli images scan --address https://${{ secrets.PATH_TO_CONSOLE }} \
                                 --user ${{ secrets.TL_USER }} \
                                 --password ${{ secrets.TL_PASS }} \
                                 --details ${{ env.DOCKER_IMAGE }}



