name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

#env:
#  PRISMA_CLOUD_URL: "https://api3.prismacloud.io"

jobs:
  security_scan:
    name: Run Checkov Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: https://api3.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}

  scan:
    name: Run Prisma Cloud Scans
    runs-on: ubuntu-latest
    needs: security_scan
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Ubuntu Image
        run: |
          docker pull ubuntu:latest
          docker run --rm ubuntu:latest echo "Ubuntu container ready for scanning"

      - name: Download and Configure TwistCLI
        run: |
          curl -k -u "${{ secrets.TL_USER }}:${{ secrets.TL_PASS }}" --output twistcli https://us-west1.cloud.twistlock.com/us-3-159214132/api/v1/util/twistcli
          sudo chmod +x twistcli
          TCLI_VERSION=$(./twistcli | grep -A1 VERSION | sed 1d | tr -d '"')
          CONSOLE_VERSION=$(curl -sk -u "${{ secrets.TL_USER }}:${{ secrets.TL_PASS }}" https://us-west1.cloud.twistlock.com/us-3-159214132/api/v1/version | tr -d '"')
          echo "TCLI_VERSION = $TCLI_VERSION"
          echo "CONSOLE_VERSION = $CONSOLE_VERSION"
          if [[ "$TCLI_VERSION" != "$CONSOLE_VERSION" ]]; then
            echo "Downloading latest TwistCLI..."
            
          fi

      - name: Run TwistCLI Image Scan
        run: |
            ./twistcli images scan --address https://us-west1.cloud.twistlock.com/us-3-159214132 --user 990c91e1-7ec0-4e59-878d-e793df85534b --password uDqCu9r+IsbqcISdG5FeYFddHzw= 
            --details ubuntu:latest    
             
